name: SaneClip
options:
  bundleIdPrefix: com.saneclip
  deploymentTarget:
    macOS: 15.0
  xcodeVersion: 16.0

configs:
  Debug: debug
  Release: release
  Release-AppStore: release

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.0.0
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.6.0

settings:
  DEAD_CODE_STRIPPING: YES
  SWIFT_EMIT_LOC_STRINGS: YES
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
  ENABLE_HARDENED_RUNTIME: YES
  GENERATE_INFOPLIST_FILE: YES
  # Recommended warnings
  CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
  CLANG_WARN_BOOL_CONVERSION: YES
  CLANG_WARN_COMMA: YES
  CLANG_WARN_CONSTANT_CONVERSION: YES
  CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
  CLANG_WARN_EMPTY_BODY: YES
  CLANG_WARN_ENUM_CONVERSION: YES
  CLANG_WARN_INFINITE_RECURSION: YES
  CLANG_WARN_INT_CONVERSION: YES
  CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
  CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
  CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
  CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
  CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
  CLANG_WARN_STRICT_PROTOTYPES: YES
  CLANG_WARN_SUSPICIOUS_MOVE: YES
  CLANG_WARN_UNREACHABLE_CODE: YES
  CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
  ENABLE_STRICT_OBJC_MSGSEND: YES
  GCC_NO_COMMON_BLOCKS: YES
  GCC_WARN_64_TO_32_BIT_CONVERSION: YES
  GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
  GCC_WARN_UNDECLARED_SELECTOR: YES
  GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
  GCC_WARN_UNUSED_FUNCTION: YES
  GCC_WARN_UNUSED_VARIABLE: YES
  SWIFT_STRICT_CONCURRENCY: complete

schemes:
  SaneClip:
    build:
      targets:
        SaneClip: all
        SaneClipTests: [test]
    test:
      targets:
        - SaneClipTests
    profile:
      config: Release
    run:
      config: Debug
    archive:
      config: Release

targets:
  SaneClip:
    type: application
    platform: macOS
    bundleId: com.saneclip.app
    deploymentTarget:
      macOS: 15.0
    sources:
      - main.swift
      - SaneClipApp.swift
      - path: Core
        excludes:
          - "**/CLAUDE.md"
      - path: UI
        excludes:
          - "**/CLAUDE.md"
      - Resources
    dependencies:
      - package: KeyboardShortcuts
      - package: Sparkle
    info:
      path: SaneClip/Info.plist
      properties:
        LSUIElement: true
        LSApplicationCategoryType: "public.app-category.productivity"
        NSAppleEventsUsageDescription: "SaneClip needs to paste clipboard content to other applications."
        # Sparkle Auto-Update Configuration (CRITICAL - was missing!)
        SUFeedURL: "https://saneclip.com/appcast.xml"
        SUPublicEDKey: "QwXgCpqQfcdZJ6BIzLRrBmn2D7cwkNbaniuIkm/DJyQ="
        SUEnableAutomaticChecks: true
        SUEnableSystemProfiling: false
    settings:
      base:
        PRODUCT_NAME: SaneClip
        PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app
        MARKETING_VERSION: "1.1"
        CURRENT_PROJECT_VERSION: "3"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        SWIFT_VERSION: 6.0
        MACOSX_DEPLOYMENT_TARGET: 15.0
        ARCHS: arm64
        VALID_ARCHS: arm64
        DEVELOPMENT_TEAM: M78L6FXD48
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_INJECT_BASE_ENTITLEMENTS: YES
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.dev
          CODE_SIGN_IDENTITY: "Apple Development"
          CODE_SIGN_ENTITLEMENTS: SaneClip/SaneClip.entitlements
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app
          CODE_SIGN_IDENTITY: "Developer ID Application: Stephan Joseph (M78L6FXD48)"
          CODE_SIGN_ENTITLEMENTS: SaneClip/SaneClip.entitlements
        Release-AppStore:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app
          CODE_SIGN_IDENTITY: "Apple Distribution"
          CODE_SIGN_ENTITLEMENTS: SaneClip/SaneClipAppStore.entitlements
          OTHER_SWIFT_FLAGS: "-D APP_STORE"
    postCompileScripts:
      - script: |
          if which swiftlint >/dev/null; then
            swiftlint . || true
          else
            echo "warning: SwiftLint not installed"
          fi
        name: Run SwiftLint
        basedOnDependencyAnalysis: false

  SaneClipTests:
    type: bundle.unit-test
    platform: macOS
    bundleId: com.saneclip.appTests
    deploymentTarget:
      macOS: 15.0
    testTarget: SaneClip
    sources:
      - Tests
    dependencies:
      - target: SaneClip
    settings:
      base:
        DEVELOPMENT_TEAM: M78L6FXD48
        CODE_SIGN_STYLE: Manual
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
        Release:
          CODE_SIGN_IDENTITY: "Apple Development"
